name: DirectionHUD
description: On screen HUD plugin that has many customizable features. Save coordinates, see death locations, track players, all at a glance!
website: https://github.com/Oth3r/DirectionHUD
version: '${version}'
author: "Oth3r"
main: one.oth3r.directionhud.DirectionHUD
api-version: 1.18
commands:
  destination:
    description: "Handles everything to do with destinations, tracking, and sharing."
    aliases: "dest"
  hud:
    description: "Handles all one.oth3r.directionhud.common.HUD actions"
  directionhud:
    description: "Base command"
    aliases: "dirhud"
permissions:
  directionhud.hud:
    description: "Permissions for the '/hud' command"
    default: true
  directionhud.destination:
    description: "Permissions for the '/destination' command"
    default: true
  directionhud.destination.saving:
    description: "Permissions for saving destinations"
    default: true
  directionhud.directionhud:
    description: "Permissions for the '/directionhud' command"
    default: true
  directionhud.reload:
    description: "Permissions for the reload command. (Requires directionhud permissions)"
  directionhud.defaults:
    description: "Permissions for the defaults command. (Requires directionhud permissions)"