name: Crowdin Upload Action

on:
  push:
    paths: [ 'common/src/main/resources/assets/directionhud/lang/en_US.json']
    branches: [ main ]
  workflow_dispatch:

jobs:
  crowdin-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin push
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}